### ISSUE TITLE
systemd and vagrant packaging interaction

### ISSUE THREAD

**Issue by meantheory** [Temelio/ansible-role-zeppelin#42]
For reasons I can't explain yet, the pid directory `/var/run/zeppelin` seems to disappear after running a `vagrant package` to generate a shareable box. The systemd service file specifies the creation of the pid directory but does so as the zeppelin user and the zeppelin user doesn't have permissions to do this. 

If you add the directive `PermissionsStartOnly=true` to the service definition, the pre tasks are run as root and the service comes up as expected after a `vagrant package`.

 - [similar issue on the unix stack exchange](https://unix.stackexchange.com/questions/207469/systemd-permission-issue-with-mkdir-execstartpre#207493)

**Comment by achaussier** [comment]
Hello,

Thanks for the report, I'll take a look next days to fix that.

**Comment by meantheory** [comment]
Thank you
